### ISSUE TITLE
Update to PHP 5.6

### ISSUE THREAD

**Issue by gbirke** [wmde/Wikipedia.de#20]
We should check if any code breaks with PHP 5.6 and then update the wikipedia.de server. This will give us slightly better security and performance and allow us to use new language features (short array syntax etc).

**Comment by wiese** [comment]
Given the relatively small code base we should shoot for an even higher version in my opinion.
http://php.net/supported-versions.php

**Comment by manicki** [comment]
+1

**Comment by wiese** [comment]
5.6 it is (already).
```
me@wmde01:~$ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
me@wmde01:~$ date
Fri Sep 22 17:11:42 CEST 2017

```
